apiVersion: 1

datasources:
  - name: sandbox-quant-postgres
    uid: sandbox-quant-postgres
    type: postgres
    access: proxy
    isDefault: true
    url: ${GRAFANA_POSTGRES_HOST}
    user: ${POSTGRES_USER}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: ${GRAFANA_POSTGRES_SSLMODE}
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
